// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Training")>]
[<assembly: AssemblyProductAttribute("Training")>]
[<assembly: AssemblyDescriptionAttribute("Problem solving in one solution")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Training"
    let [<Literal>] AssemblyProduct = "Training"
    let [<Literal>] AssemblyDescription = "Problem solving in one solution"
    let [<Literal>] AssemblyConfiguration = "Release"
